{% set name = "pywapor" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pywapor-{{ version }}.tar.gz
  sha256: e3dd62a271dd9ffbdc16dce6008f8f4c2e0f8b90bf21945b99920e7a90e2fba2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - netcdf4
    - gdal
    - xarray
    - numpy
    - pandas
    - requests
    - matplotlib-base
    - pyproj
    - scipy
    - pycurl
    - joblib
    - bs4
    - beautifulsoup4
    - rasterio
    - bottleneck
    - tqdm
    - dask-core
    - rioxarray
    - cryptography
    - cachetools
    - cdsapi
    - shapely
    - lxml
    - scikit-learn
    - numba
    - xmltodict

test:
  imports:
    - pywapor

about:
  summary: Collect input data and run ETLook.
  home: https://www.fao.org/aquastat/py-wapor/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bertcoerver
